[2025-01-09T14:35:53.337+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-09T14:35:53.341+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_airflow.say_hello scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-01-09T14:35:53.345+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_airflow.say_hello scheduled__2025-01-08T00:00:00+00:00 [queued]>
[2025-01-09T14:35:53.345+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-01-09T14:35:53.350+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): say_hello> on 2025-01-08 00:00:00+00:00
[2025-01-09T14:35:53.352+0000] {standard_task_runner.py:57} INFO - Started process 169 to run task
[2025-01-09T14:35:53.353+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'hello_***', 'say_hello', 'scheduled__2025-01-08T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/hello_***.py', '--cfg-path', '/tmp/tmpf11mfty5']
[2025-01-09T14:35:53.354+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask say_hello
[2025-01-09T14:35:53.361+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-09T14:35:53.377+0000] {task_command.py:410} INFO - Running <TaskInstance: hello_airflow.say_hello scheduled__2025-01-08T00:00:00+00:00 [running]> on host cdb64526c5e5
[2025-01-09T14:35:53.383+0000] {logging_mixin.py:149} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-09T14:35:53.420+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_***' AIRFLOW_CTX_TASK_ID='say_hello' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-08T00:00:00+00:00'
[2025-01-09T14:35:53.421+0000] {logging_mixin.py:149} INFO - Hello, Airflow!
[2025-01-09T14:35:53.422+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-01-09T14:35:53.446+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=hello_***, task_id=say_hello, execution_date=20250108T000000, start_date=20250109T143553, end_date=20250109T143553
[2025-01-09T14:35:53.495+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-01-09T14:35:53.514+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
